# EDA na pr√°tica! üòé

### **Descri√ß√£o:**
Agora que voc√™ j√° sabe os b√°sicos do por qu√™ precisamos de dados limpos, bem estruturados e como trabalhar com um conjunto de dados at√© chegar nessa etapa, que tal testar as nossas novas habilidades em um dataset real? Hoje, o nosso objetivo ser√° limpar e extrair alguns insights do conjunto de dados da trag√©dia mais esquisita do mundo das navega√ß√µes, o [Titanic](https://www.kaggle.com/c/titanic/overview)! Esse dataset vai incluir as seguintes informa√ß√µes:

|                Coluna                | Descri√ß√£o |
|:------------------------------------:|:---------:|
|                  Survived                 |    Sobreviv√™ncia ou n√£o (0 - n√£o; 1- sim)       |
|                  Pclass                 |    Tipo de passagem (1a, 2a ou 3a classe)    |
|          SibSp   |    No. de irm√£os/c√¥njuges a bordo do Titanic       |
| Parch |    No. de pais/filhos a bordo do Titanic       |
|      Ticket   |      No. do t√≠quete    |
|       Fare       |    Tarifa de passageiro       |
|                Cabin               |       N√∫mero da cabine    |
|    Embarked  |      Porto de embarca√ß√£o (C - Cherbourg, Q - Queenstown, S - Southampton)     |


Essa pr√≥xima etapa deve deixar algumas pessoas com frio na barriga, mas relaxa que temos tempo mais que suficiente para explorar esses dados.
#### Ps: Esse √© muito melhor de entender do que o dos cachorros üòâ

### 1.1 - Leitura dos dados e realiza√ß√£o de descri√ß√£o estat√≠stica
---

A seguir, o dataframe j√° estar√° montado pelo m√©todo `pd.read_csv()` da biblioteca `pandas`, a partir da execu√ß√£o da c√©lula.

Dica: Voc√™ pode acessar a documenta√ß√£o da biblioteca `pandas` [clicando aqui](https://pandas.pydata.org/docs/getting_started/index.html#getting-started). Ap√≥s o processamento do dataframe, voc√™ ter√° de realizar uma descri√ß√£o estat√≠stica dos dados.
/
#### Lembrando! A descri√ß√£o estat√≠stica nada mais √© do que mostrar como os valores est√£o distribu√≠dos, ent√£o pode usar quaisquer m√©todo achar suficiente para fazer isso, e lembrando, **menos e melhor** √© a chave para uma boa an√°lise! üòÅ

In [ ]:
import pandas as pd

In [ ]:
dataset = pd.read_csv('https://raw.githubusercontent.com/IcaroR/TRILha/main/datasets/Titanic/train.csv', sep = ',')
dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# Seu c√≥digo aqui

### 1.2 - Limpeza dos dados
---

Agora que j√° conseguimos ter uma vis√£o do panor√¢mica dos dados, conseguimos ver que eles est√£o uma porcaria, ent√£o que tal dar uma faxina neles? Remova todos os erros, como dados faltantes, colunas com tipos errados, etc. Mais uma vez, a leitura da documenta√ß√£o do `pandas` √© imprescind√≠vel.

_Sua resposta aqui_

In [ ]:
# Seu c√≥digo aqui

### 1.3 - An√°lise Explorat√≥ria dos Dados
---

Ufa! Finalmente demos uma bela limpada naquela bagun√ßa, agora √© hora de **REALMENTE** dar uma olhada no que t√° acontecendo aqui. A primeira coisa que vamos fazer √© procurar algumas correla√ß√µes e analizar as distribui√ß√µes das features que est√£o presentes nesse dataset. Pra fazer isso, recomendo usar a biblioteca `matplotlib.pyplot` para criar gr√°ficos que representem estas medidas. Agora, se voc√™ conhecer alguma outra ferramenta que te ajude aqui, pode ir fundo nela!
Lembrando, use todos os gr√°ficos que achar necess√°rio, mas n√£o precisa exagerar tamb√©m, beleza?
Ajude seu monitor! üíÄ

In [ ]:
# Seu c√≥digo aqui

### 1.4 - Feature Engineering e Dados Categ√≥ricos
---

1.4.1 - Sempre que falamos de _Data Science_, j√° lembramos de tipos diferentes de dados, e com eles, sempre vem os temidos dados categ√≥rios. Esse tipo de dados normalmente apresenta uma forma muito diferente de vari√°veis num√©ricas, e por consqu√™ncia, trabalhar com eles tab√©m exige um cuidado a mais. Por isso, agora vamos transformar alguns desses dados usando os m√©todos que a gente aprendeu hoje, um deles sendo o OneHotEncoder. Pss, ainda lembra como ele funciona? ü§î

Ap√≥s isso, vamos fazer o _Feature Engineering_! Essa √© uma t√©cnica **PODEROS√çSSIMA** que vai ajudar a gente a conseguir algumas outras informa√ß√µes que vimos ser poss√≠veis de extrair no passo `1.3`.
Agora, basta usar sua intui√ß√£o e criatividade para decidir como novos atributos podem ser definidos, a partir das informa√ß√µes que j√° temos.

Dica: Use as colunas existentes para gerar uma ou mais colunas com atributos distintos dos primeiros.

In [ ]:
# Seu c√≥digo aqui

1.4.2 - Em poucos termos, computadores n√£o conseguem entender texto de maneira alguma, mas n√∫meros, ah, esses as m√°quinas entendem bem pra caramba!
Ent√£o, que tal usar as t√©cnicas que aprendemos pra deixar tudo necess√°rio em n√∫meros?

Dica: Sempre que temos uma feature categ√≥rica que possui apenas 2 elementos, podemos transformar ela em uma flag bin√°ria!
Agora o que isso significa eu deixo pra voc√™ pesquisar üòâ

In [ ]:
# Seu c√≥digo aqui